# Generated by Django 6.0.3 on 2026-03-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('IT', 'IT'), ('NON-IT', 'Non-IT')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skills_required', models.TextField(help_text='Comma separated skills, e.g., Python, Django, SQL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
